services:
  app:
    build:
      context: ./docker/php
    volumes:
      - type: bind
        source: ${APP_PATH}
        target: /usr/local/src/${APP_NAME}/src
      - type: bind
        source: ${DOCKER_PATH}/php/php.ini
        target: /usr/local/etc/php/php.ini
    working_dir: /usr/local/src/${APP_NAME}/src

  web:
    image: nginx:1.25
    ports:
      - ${WEB_PORT}:80
    volumes:
      - type: bind
        source: ${APP_PATH}
        target: /usr/local/src/${APP_NAME}/src
      - type: bind
        source: ${DOCKER_PATH}/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
    working_dir: /usr/local/src/${APP_NAME}/src
